services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d","${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - e-commerce-network



  app:
    build: .
    container_name: e-commerce
    env_file:
      .env
    environment:
      SPRING_PROFILES_ACTIVE: container
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - e-commerce-network


volumes:
  postgres-data:
    driver: local
  pgadmin-data:

networks:
  e-commerce-network:
    driver: bridge